[[main]]
    name = "Follow Us"
    weight = 80
[[main]]
    parent = "Follow Us"
    name = "Newsletter"
    weight = 81
    url = "#"
[[main]]
    parent = "Follow Us"
    name = "Blogs"
    weight = 82
    url = "#"
[[main]]
    parent = "Follow Us"
    name = "Astrophotography"
    weight = 83
    url = "#"
[[main]]
    parent = "Follow Us"
    name = "Twitter"
    weight = 84
    url = "https://twitter.com/starryskysouth"
[[main]]
    parent = "Follow Us"
    name = "Facebook"
    weight = 85
    url = "https://www.facebook.com/groups/1012753086040435"
