backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"

public_folder: "/images/uploads"

site_url: https://starryskiessouth.github.io

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - label: "Site Configs"
    name: "configs"
    files:
      - name: homepage
        label: "Homepage"
        file: data/homepage.yml
        fields:
          - label: "Banner"
            widget: "object"
            name: "banner"
            fields:
              - label: "Enable"
                name: "enable"
                widget: "boolean"
                default: "true"
              - label: "Image"
                name: "image"
                widget: "image"
                allow_multiple: false
                required: false
              - label: "Subtext"
                name: "contents"
                widget: "markdown"
              - label: "Button"
                name: "button"
                widget: "object"
                fields:
                  - label: "Text"
                    name: "contents"
                    widget: "string"
                    default: "Learn More"
                  - label: "URL"
                    name: "url"
                    widget: "string"
                    default: "/about/mission"
          - label: "Icon Card Section"
            name: "items"
            widget: "list"
            fields:
              - label: "Type"
                name: "type"
                widget: "string"
                default: "highlights"
              - label: "Items Per Row"
                name: "items_per_row"
                widget: "number"
                value_type: "int"
                default: 3
              - label: "Cards"
                name: "items"
                widget: "list"
                summary: '{{fields.title}}'
                allow_add: true
                collapsed: true
                fields:
                  - label: "Title"
                    name: "title"
                    widget: "string"
                    default: "ITEM TITLE"
                  - label: "Icon (fontawesome)"
                    name: "icon"
                    widget: "string"
                    default: "fa-lightbulb"
                  - label: "Content"
                    name: "content"
                    widget: "text"
                    default: "Some cool explanation"
      - name: title
        file: data/globalheader.yml
        label: "Main Page Title"
        fields:
          - label: "Title"
            name: "title"
            widget: "markdown"
            default: "Starry Skies South"
  - name: root
    folder: content/
    create: true
    label: "Root Pages"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Subtitle"
        name: "description"
        widget: "string"
        required: false
      - label: "Menu"
        name: "menu"
        widget: "string"
        default: "main"
      - label: "Image"
        name: "image"
        widget: "image"
        allow_multiple: false
        required: false
      - label: "Image Alt Text"
        name: "image_alt"
        widget: "string"
        required: false
      - label: "Date"
        name: "date"
        widget: "date"
        format: "YYYY-MM-DD"
      - label: "Weight (for sorting, lower values come first)"
        name: "weight"
        widget: "number"
        value_type: "int"
        default: 500
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: about
    folder: content/about
    create: true
    label: "About Us"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Subtitle"
        name: "description"
        widget: "string"
        required: false
      - label: "Image"
        name: "image"
        widget: "image"
        allow_multiple: false
        required: false
      - label: "Image Alt Text"
        name: "image_alt"
        widget: "string"
        required: false
      - label: "Date"
        name: "date"
        widget: "date"
        format: "YYYY-MM-DD"
      - label: "Weight (for sorting, lower values come first)"
        name: "weight"
        widget: "number"
        value_type: "int"
        default: 260
      - label: "Left Sidebar"
        name: "sidebar_left"
        widget: "select"
        options: ["", "list"]
        default: ""
        required: false
      - label: "Right Sidebar"
        name: "sidebar_right"
        widget: "select"
        options: ["", "list"]
        default: "list"
        required: false
      - label: "Main Menu Parent"
        name: "menu"
        widget: "object"
        fields:
          - label: "Main Menu"
            name: "main"
            widget: "object"
            fields:
              - label: "Parent Menu"
                name: "parent"
                default: "About Us"
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: preserving
    folder: content/preserving
    create: true
    label: "Preserving Starry Skies"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Subtitle"
        name: "description"
        widget: "string"
        required: false
      - label: "Image"
        name: "image"
        widget: "image"
        allow_multiple: false
        required: false
      - label: "Image Alt Text"
        name: "image_alt"
        widget: "string"
        required: false
      - label: "Date"
        name: "date"
        widget: "date"
        format: "YYYY-MM-DD"
      - label: "Weight (for sorting, lower values come first)"
        name: "weight"
        widget: "number"
        value_type: "int"
        default: 450
      - label: "Left Sidebar"
        name: "sidebar_left"
        widget: "select"
        options: ["", "list"]
        default: ""
        required: false
      - label: "Right Sidebar"
        name: "sidebar_right"
        widget: "select"
        options: ["", "list"]
        default: "list"
        required: false
      - label: "Main Menu Parent"
        name: "menu"
        widget: "object"
        fields:
          - label: "Main Menu"
            name: "main"
            widget: "object"
            fields:
              - label: "Parent Menu"
                name: "parent"
                default: "Preserve Starry Skies"
      - label: "Body"
        name: "body"
        widget: "markdown"
